from django.shortcuts import get_object_or_404, redirect, render
from payroll.models import Payslip


def list_payslip(request):...

def create_paysplip(request):...

def update_payslip(request):...

def delete_payslip(request):...