# Generated by Django 5.2 on 2025-05-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_alter_employee_salary_alter_payslip_bonus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="dni",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
