# Generated by Django 5.2 on 2025-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_alter_employee_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
