# Generated by Django 5.2.1 on 2025-05-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_tipopermiso_permiso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='empleado',
            new_name='employee',
        ),
    ]
